// ParikshaSathi — app.js (auto-generated by build.py)
// By Er. Sangam Krishna
// DO NOT EDIT DIRECTLY — edit chunks/ files and run build.py


// ═══ chunks/c01.js ═══
// ParikshaSathi — Smart Study Planner | By Er. Sangam Krishna
let selectedExam='',userData={},studyPlan=[];

function showScreen(id){
  document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));
  document.getElementById(id).classList.add('active');
  window.scrollTo(0,0);
}

function selectExam(exam){
  selectedExam=exam;
  const bg=document.getElementById('bpscClassGroup');
  if(exam==='bpsc'){
    bg.classList.remove('hidden');
    document.getElementById('formHeaderIcon').textContent='🏫';
    document.getElementById('formTitle').textContent='BPSC TRE 4.0 — जानकारी भरें';
    document.getElementById('formSubtitle').textContent='Class 1-5 (PRT) या 6-8 (TGT) चुनें और plan पाएं';
    document.getElementById('nameNum').textContent='02';
    document.getElementById('dateNum').textContent='03';
    document.getElementById('hoursNum').textContent='04';
    document.getElementById('slotNum').textContent='05';
  } else {
    bg.classList.add('hidden');
    document.getElementById('formHeaderIcon').textContent='🏛️';
    document.getElementById('formTitle').textContent='UPSC CSE 2027 — जानकारी भरें';
    document.getElementById('formSubtitle').textContent='Prelims + Mains का personalized plan पाएं';
    document.getElementById('nameNum').textContent='01';
    document.getElementById('dateNum').textContent='02';
    document.getElementById('hoursNum').textContent='03';
    document.getElementById('slotNum').textContent='04';
  }
  showScreen('formScreen');
}

function showTab(tabName){
  document.querySelectorAll('.tab-content').forEach(t=>t.classList.remove('active'));
  document.querySelectorAll('.tab-btn').forEach(b=>b.classList.remove('active'));
  document.getElementById(tabName).classList.add('active');
  document.querySelectorAll('.tab-btn').forEach(b=>{
    if(b.getAttribute('onclick')===`showTab('${tabName}')`) b.classList.add('active');
  });
}

function toggleAccordion(el){
  const body=el.nextElementSibling;
  const arrow=el.querySelector('.syl-arrow');
  body.classList.toggle('open');
  arrow.style.transform=body.classList.contains('open')?'rotate(180deg)':'rotate(0deg)';
}

// ═══ chunks/c02.js ═══
// SYLLABUS DATA — BPSC Class 1-5 (PRT)
// Pattern: Part I Language(30) + Part II GS(120) = 150 marks. No negative marking.
// Language is qualifying — kept last so GS subjects get priority in rotation.
const syl_bpsc15 = {

  'Part II — General Studies (सामान्य अध्ययन)': {
    marks:120, color:'#10b981',
    topics:[

      // ── MATHEMATICS (split into 10 focused topics, 1-2 concepts each) ──
      {name:'Maths: Number System & Simplification',hindi:'संख्या पद्धति एवं सरलीकरण',
       micro:['Natural, Whole, Integer, Rational, Irrational numbers',
              'LCM & HCF — methods and shortcuts',
              'Divisibility rules (2,3,4,5,6,8,9,11)',
              'BODMAS — order of operations',
              'Simplification of fractions and decimals',
              'Practice: 10 questions on number system']},

      {name:'Maths: Percentage & Its Applications',hindi:'प्रतिशत एवं उसके अनुप्रयोग',
       micro:['Percentage — basic concept and formula',
              'Percentage increase / decrease',
              'Percentage of a quantity',
              'Converting fraction ↔ percentage ↔ decimal',
              'Application in marks, population, discount',
              'Practice: 10 questions on percentage']},

      {name:'Maths: Profit, Loss & Discount',hindi:'लाभ, हानि एवं छूट',
       micro:['Cost Price, Selling Price, Marked Price',
              'Profit % and Loss % formulas',
              'Discount — single and successive',
              'Finding CP when SP and profit% given',
              'Dishonest dealer problems',
              'Practice: 10 questions on profit-loss']},

      {name:'Maths: Simple & Compound Interest',hindi:'साधारण एवं चक्रवृद्धि ब्याज',
       micro:['SI formula — P×R×T/100',
              'CI formula — P(1+R/100)^T',
              'Difference between SI and CI',
              'Finding Principal, Rate, Time',
              'Half-yearly and quarterly compounding',
              'Practice: 10 questions on interest']},

      {name:'Maths: Ratio, Proportion & Average',hindi:'अनुपात, समानुपात एवं औसत',
       micro:['Ratio — simplification and comparison',
              'Proportion — direct and inverse',
              'Partnership problems',
              'Average formula and weighted average',
              'Average of consecutive numbers',
              'Practice: 10 questions on ratio & average']},

      {name:'Maths: Time, Work & Speed-Distance',hindi:'समय, कार्य एवं चाल-दूरी',
       micro:['Time & Work — basic formula (1/n per day)',
              'Pipes & Cisterns',
              'Speed = Distance / Time',
              'Relative speed — same and opposite direction',
              'Train problems (length + speed)',
              'Practice: 10 questions on time-work-speed']},

      {name:'Maths: Algebra & Linear Equations',hindi:'बीजगणित एवं रैखिक समीकरण',
       micro:['Algebraic expressions — addition, subtraction',
              'Identities: (a+b)², (a-b)², (a+b)(a-b)',
              'Factorisation',
              'Linear equations in one variable',
              'Linear equations in two variables',
              'Practice: 10 questions on algebra']},

      {name:'Maths: Geometry — Lines, Angles & Triangles',hindi:'रेखागणित — रेखाएं, कोण एवं त्रिभुज',
       micro:['Types of angles — acute, obtuse, right, reflex',
              'Parallel lines and transversal',
              'Properties of triangles',
              'Congruence and similarity of triangles',
              'Pythagoras theorem and applications',
              'Practice: 10 questions on geometry']},

      {name:'Maths: Mensuration — Area & Perimeter',hindi:'क्षेत्रमिति — क्षेत्रफल एवं परिमाप',
       micro:['Rectangle, Square — area and perimeter',
              'Triangle — area (base×height/2, Heron\'s formula)',
              'Circle — area (πr²) and circumference (2πr)',
              'Parallelogram and Trapezium',
              'Combined figures',
              'Practice: 10 questions on 2D mensuration']},

      {name:'Maths: Mensuration — Volume & Surface Area',hindi:'क्षेत्रमिति — आयतन एवं पृष्ठ क्षेत्रफल',
       micro:['Cube and Cuboid — volume and surface area',
              'Cylinder — volume and curved surface area',
              'Cone — volume and slant height',
              'Sphere and Hemisphere',
              'Problems on capacity and cost',
              'Practice: 10 questions on 3D mensuration']},

      // ── REASONING (split into 4 focused topics) ──
      {name:'Reasoning: Series, Analogy & Classification',hindi:'श्रृंखला, सादृश्यता एवं वर्गीकरण',
       micro:['Number Series — find missing/wrong term',
              'Letter Series — alphabetical patterns',
              'Analogy — number, letter, word based',
              'Classification (Odd one out)',
              'Mixed series problems',
              'Practice: 10 questions']},

      {name:'Reasoning: Coding, Blood Relations & Direction',hindi:'कूट भाषा, रक्त संबंध एवं दिशा ज्ञान',
       micro:['Coding-Decoding — letter shift, symbol based',
              'Blood Relations — family tree method',
              'Direction Sense — 8 directions, distance',
              'Ranking & Order (top/bottom, left/right)',
              'Practice: 10 questions']},

      {name:'Reasoning: Logical & Verbal Reasoning',hindi:'तार्किक एवं मौखिक तर्क',
       micro:['Statement & Conclusion',
              'Statement & Assumption',
              'Syllogism — Venn diagram method',
              'Cause & Effect',
              'Course of Action',
              'Practice: 10 questions']},

      {name:'Reasoning: Non-Verbal & Miscellaneous',hindi:'अशाब्दिक तर्क एवं विविध',
       micro:['Sitting Arrangement — linear and circular',
              'Venn Diagram — set-based problems',
              'Calendar — day/date problems',
              'Clock — angle and time problems',
              'Mirror & Water Image',
              'Practice: 10 questions']},

      // ── HISTORY (Ancient + Medieval + Modern — all are in BPSC TRE GS) ──
      {name:'History: Ancient India',hindi:'प्राचीन भारत का इतिहास',
       micro:['Indus Valley Civilisation — Harappa, Mohenjo-daro',
              'Vedic Age — Rigveda, Upanishads, Aryan society',
              'Mahajanapadas — 16 kingdoms, Magadha rise',
              'Maurya Empire — Chandragupta, Ashoka, Dhamma',
              'Gupta Empire — Golden Age, science & art',
              'Buddhism & Jainism — founders, teachings, spread',
              'Important dynasties — Kushana, Satavahana, Chola']},

      {name:'History: Medieval India',hindi:'मध्यकालीन भारत का इतिहास',
       micro:['Delhi Sultanate — Slave, Khilji, Tughlaq, Lodi dynasties',
              'Mughal Empire — Babur to Aurangzeb',
              'Akbar\'s administration — Mansabdari, Din-i-Ilahi',
              'Bhakti Movement — Kabir, Mirabai, Tulsidas, Ramananda',
              'Sufi Movement — Chishti, Suhrawardi orders',
              'Vijayanagara Empire',
              'Maratha Empire — Shivaji, Peshwas']},

      {name:'History: Modern India & Freedom Movement',hindi:'आधुनिक भारत एवं स्वतंत्रता संग्राम',
       micro:['British East India Company — Plassey, Buxar',
              '1857 Revolt — causes, events, leaders',
              'Indian National Congress — formation 1885',
              'Gandhi — Champaran, Non-Cooperation, Civil Disobedience, Quit India',
              'Bihar in Freedom Movement — JP, Rajendra Prasad',
              'Partition 1947 and Independence',
              'Important Acts — 1919, 1935, 1947']},

      // ── GEOGRAPHY ──
      {name:'Geography: India — Physical & Climate',hindi:'भारत का भौतिक भूगोल एवं जलवायु',
       micro:['Location, extent and neighbours of India',
              'Physiographic divisions — Himalayas, Plains, Plateau, Coastal',
              'Major rivers — Ganga, Yamuna, Brahmaputra, Deccan rivers',
              'Climate — Monsoon, seasons, rainfall distribution',
              'Natural vegetation and wildlife',
              'Bihar geography — rivers, plains, districts']},

      {name:'Geography: India — Resources & Economy',hindi:'भारत के संसाधन एवं अर्थव्यवस्था',
       micro:['Soil types — alluvial, black, red, laterite',
              'Agriculture — major crops, crop seasons (Kharif/Rabi)',
              'Minerals — coal, iron ore, bauxite, mica',
              'Industries — iron & steel, textile, IT',
              'Transport — railways, roadways, waterways',
              'Population — census, density, literacy']},

      // ── POLITY ──
      {name:'Polity: Constitution & Fundamental Rights',hindi:'संविधान एवं मौलिक अधिकार',
       micro:['Making of Constitution — Constituent Assembly',
              'Preamble — key words and significance',
              'Fundamental Rights — Articles 12–35',
              'Directive Principles of State Policy (DPSP)',
              'Fundamental Duties',
              'Important Amendments — 42nd, 44th, 73rd, 74th, 86th']},

      {name:'Polity: Government Structure',hindi:'सरकार की संरचना',
       micro:['President — election, powers, Article 52–78',
              'Prime Minister and Council of Ministers',
              'Parliament — Lok Sabha, Rajya Sabha, functions',
              'Supreme Court and High Courts',
              'Panchayati Raj — 73rd Amendment, 3-tier system',
              'Urban Local Bodies — 74th Amendment',
              'Election Commission — functions and powers']},

      // ── ECONOMICS ──
      {name:'Economics: Indian Economy Basics',hindi:'भारतीय अर्थव्यवस्था की मूल बातें',
       micro:['Types of economy — capitalist, socialist, mixed',
              'National Income — GDP, GNP, NNP',
              'Five Year Plans and NITI Aayog',
              'Poverty and unemployment — types and measures',
              'Inflation — causes, effects, control',
              'Banking — RBI, commercial banks, functions',
              'Government schemes — PM-KISAN, MGNREGA, Ayushman Bharat']},

      // ── SCIENCE ──
      {name:'Science: Physics — Motion, Force & Energy',hindi:'भौतिकी — गति, बल एवं ऊर्जा',
       micro:['Motion — distance, displacement, speed, velocity',
              'Newton\'s Laws of Motion',
              'Work, Energy and Power',
              'Gravitation — free fall, g value',
              'Pressure — Pascal\'s law, atmospheric pressure',
              'Sound — properties, echo, ultrasound']},

      {name:'Science: Physics — Light, Heat & Electricity',hindi:'भौतिकी — प्रकाश, ऊष्मा एवं विद्युत',
       micro:['Reflection and Refraction of Light',
              'Lenses and Mirrors — concave, convex',
              'Human Eye — defects and correction',
              'Heat — conduction, convection, radiation',
              'Electric current — Ohm\'s law, resistance',
              'Magnetic effects of current']},

      {name:'Science: Chemistry',hindi:'रसायन विज्ञान',
       micro:['Matter — states, properties, changes',
              'Atoms and Molecules — atomic structure',
              'Periodic Table — groups, periods, key elements',
              'Acids, Bases and Salts — pH scale',
              'Metals and Non-Metals — properties and uses',
              'Carbon compounds — organic basics',
              'Chemical reactions — types and examples']},

      {name:'Science: Biology — Life Processes',hindi:'जीव विज्ञान — जीवन प्रक्रियाएं',
       micro:['Cell — structure, organelles, cell division',
              'Nutrition — autotrophic, heterotrophic, photosynthesis',
              'Respiration — aerobic and anaerobic',
              'Transportation — blood, heart, circulatory system',
              'Excretion — kidneys, nephron',
              'Nervous System — brain, spinal cord, reflex action']},

      {name:'Science: Biology — Reproduction & Environment',hindi:'जीव विज्ञान — जनन एवं पर्यावरण',
       micro:['Reproduction — asexual and sexual',
              'Heredity and Evolution — Mendel\'s laws',
              'Vitamins and Minerals — sources and deficiency diseases',
              'Diseases — bacterial, viral, protozoan, deficiency',
              'Ecosystem — food chain, food web, energy flow',
              'Environmental pollution — types and control',
              'Conservation — biodiversity, national parks']},

      // ── CURRENT AFFAIRS & BIHAR GK ──
      {name:'Bihar GK & Current Affairs',hindi:'बिहार सामान्य ज्ञान एवं समसामयिकी',
       micro:['Bihar — history, geography, districts, rivers',
              'Bihar government schemes — Mukhyamantri schemes',
              'Bihar economy — agriculture, industries',
              'Important personalities from Bihar',
              'National current affairs — last 6 months',
              'Government schemes — central and state',
              'Sports, awards, summits — recent events']}
    ]
  },

  // ── LANGUAGE — kept last (qualifying paper, scheduled after all GS subjects) ──
  'Part I — Language (भाषा)': {
    marks:30, color:'#f59e0b',
    topics:[
      {name:'English Grammar & Comprehension',hindi:'अंग्रेजी व्याकरण एवं बोध',
       micro:['Vocabulary — Synonyms, Antonyms, One-word substitution',
              'Grammar — Noun, Pronoun, Verb, Adverb, Adjective, Preposition',
              'Articles (a, an, the) and Tenses (all 12 types)',
              'Voice — Active & Passive',
              'Narration — Direct & Indirect',
              'Sentence Correction & Transformation',
              'Reading Comprehension and Idioms & Phrases']},
      {name:'Hindi / Urdu / Bangla Grammar',hindi:'हिंदी / उर्दू / बांग्ला व्याकरण',
       micro:['वर्तनी (Spelling) और रिक्त स्थान पूर्ति',
              'शब्दावली — विलोम, समानार्थी शब्द',
              'वाक्य की बनावट और व्याकरण',
              'मुहावरेदार प्रयोग और त्रुटि पहचान',
              'बुनियादी लेखन क्षमता']}
    ]
  }
};

// ═══ chunks/c03.js ═══
// BPSC 1-5 GS continued topics
const syl_bpsc15_extra = [
  {name:'Social Studies — History',hindi:'सामाजिक अध्ययन — इतिहास',
   micro:['Ancient India — Indus Valley, Vedic, Maurya, Gupta',
          'Medieval India — Delhi Sultanate, Mughal, Bhakti-Sufi',
          'Modern India — British rule, 1857 Revolt',
          'Indian National Movement — INC, Non-Cooperation, Civil Disobedience, Quit India',
          'Role of Bihar — Champaran, JP Narayan, Rajendra Prasad']},
  {name:'Social Studies — Geography',hindi:'सामाजिक अध्ययन — भूगोल',
   micro:['Solar System & Earth','Continents & Oceans',
          'Volcano & Earthquake','Indian Geography — Mountains, Plateaus, Plains, Rivers',
          'Climate & Monsoon','Soils & Agriculture','Bihar Geography','Human Geography']},
  {name:'Social Studies — Civics / Polity',hindi:'सामाजिक अध्ययन — नागरिक शास्त्र',
   micro:['Indian Constitution — Preamble, Fundamental Rights, DPSP',
          'Parliament — Lok Sabha, Rajya Sabha',
          'President & Prime Minister','Judiciary — Supreme Court',
          'Panchayati Raj (73rd, 74th Amendment)',
          'Election Commission','Local Government']},
  {name:'Environment & EVS',hindi:'पर्यावरण एवं EVS',
   micro:['Ecosystem — Food chain, Energy flow',
          'Biodiversity — Hotspots, IUCN','Pollution — Air, Water, Soil, Noise',
          'Climate Change — Greenhouse, Ozone','Natural Disasters',
          'Conservation — National Parks, Sanctuaries','EVS Pedagogy']},
  {name:'Indian National Movement',hindi:'भारतीय राष्ट्रीय आंदोलन',
   micro:['India on Eve of British Conquest',
          'British Conquest of Bengal & Mysore',
          '1857 Revolt — Causes, Events, Leaders',
          'Foundation of Indian National Congress',
          'Era of Militant Nationalism 1905-1909',
          'Revolutionary Activities 1907-1917',
          'Emergence of Gandhi','Non-Cooperation & Khilafat Movement',
          'Civil Disobedience & Quit India Movement']},
  {name:'General Awareness',hindi:'सामान्य जागरूकता',
   micro:['India & Neighboring Countries','Current Affairs',
          'Sports — Olympics, CWG, Asian Games','History & Culture',
          'Economic Science','Government Policies & Schemes',
          'Bihar GK','Science & Technology News','Awards & Honours']}
];
// Merge into syl_bpsc15
syl_bpsc15['Part II — General Studies (सामान्य अध्ययन)'].topics.push(...syl_bpsc15_extra);

// ═══ chunks/c04.js ═══
// SYLLABUS DATA — BPSC Class 6-8 (TGT)
// Pattern: Part I Language(30) + Part II GS(40) + Part III Subject(80) = 150. No negative marking.
const syl_bpsc68 = {
  'Part I — Language (भाषा)': {
    marks:30, color:'#f59e0b',
    topics:[
      {name:'English Grammar & Comprehension',hindi:'अंग्रेजी व्याकरण एवं बोध',
       micro:['Vocabulary — Synonyms, Antonyms, One-word substitution',
              'Grammar — Noun, Pronoun, Verb, Adverb, Adjective, Preposition',
              'Articles, Tenses, Voice, Narration',
              'Sentence Correction','Reading Comprehension','Idioms & Phrases']},
      {name:'Hindi / Urdu / Bangla Grammar',hindi:'हिंदी / उर्दू / बांग्ला व्याकरण',
       micro:['वर्तनी, रिक्त स्थान पूर्ति','शब्दावली, वाक्य संरचना',
              'विलोम-समानार्थी शब्द','मुहावरेदार प्रयोग',
              'त्रुटि पहचान','बुनियादी लेखन क्षमता']}
    ]
  },
  'Part II — General Studies (सामान्य अध्ययन)': {
    marks:40, color:'#10b981',
    topics:[
      {name:'Elementary Mathematics',hindi:'प्रारंभिक गणित',
       micro:['Number System','Percentage, Profit & Loss',
              'Simple & Compound Interest','Time & Work, Ratio & Proportion',
              'Speed Distance Time','Average, Algebra, Mensuration, Geometry']},
      {name:'Mental Ability & Reasoning',hindi:'मानसिक क्षमता एवं तर्क',
       micro:['Analogies, Series, Classification',
              'Blood Relations, Coding-Decoding',
              'Direction Sense, Statement & Conclusion',
              'Sitting Arrangement, Syllogism, Ranking']},
      {name:'General Awareness & Science',hindi:'सामान्य जागरूकता एवं विज्ञान',
       micro:['India & Neighboring Countries','Current Affairs, Sports',
              'History & Culture, Economic Science',
              'Government Policies, Bihar GK',
              'Physics, Chemistry, Biology basics']},
      {name:'Social Studies & Geography',hindi:'सामाजिक अध्ययन एवं भूगोल',
       micro:['Indian & World Geography','Indian History',
              'Indian Polity & Constitution','Environment & EVS','Bihar Geography']},
      {name:'Indian National Movement',hindi:'भारतीय राष्ट्रीय आंदोलन',
       micro:['1857 Revolt, Foundation of INC',
              'Militant Nationalism, Gandhi & Mass Movements',
              'Non-Cooperation, Civil Disobedience, Quit India','Role of Bihar']}
    ]
  },
  'Part III — Subject Concerned (विषय विशेष)': {
    marks:80, color:'#8b5cf6',
    topics:[
      {name:'Mathematics & Science (Class 6-8 NCERT)',hindi:'गणित एवं विज्ञान (कक्षा 6-8)',
       micro:['Integers & Rational Numbers','Fractions & Decimals',
              'Linear Equations (रैखिक समीकरण)',
              'Geometry — Lines, Angles, Triangles, Quadrilaterals',
              'Mensuration — Area, Volume, Surface Area',
              'Data Handling — Graphs & Charts','Exponents & Powers',
              'Ratio, Proportion & Percentage',
              'Food & Nutrition, Materials & Classification',
              'Living World — Plants & Animals','Motion & Force',
              'Natural Phenomena, Natural Resources',
              'Basic Physics, Chemistry, Biology (Class 6-8 level)']},
      {name:'Social Science (Class 6-8 NCERT)',hindi:'सामाजिक विज्ञान (कक्षा 6-8)',
       micro:['Our Pasts I, II, III (History Class 6-8)',
              'Ancient & Medieval Civilizations',
              'Modern Indian History, Freedom Struggle',
              'The Earth Our Habitat (Geography Class 6)',
              'Our Environment (Geography Class 7)',
              'Resources & Development (Geography Class 8)',
              'Social & Political Life I, II, III (Civics)',
              'Democracy, Constitution & Rights, Local Government']},
      {name:'Hindi (Class 6-8 NCERT)',hindi:'हिंदी (कक्षा 6-8)',
       micro:['वसंत भाग 1, 2, 3','दूर्वा भाग 1, 2, 3','बाल महाभारत',
              'व्याकरण एवं साहित्य','बोध एवं लेखन कौशल','सांस्कृतिक संदर्भ']},
      {name:'English (Class 6-8 NCERT)',hindi:'अंग्रेजी (कक्षा 6-8)',
       micro:['Honeysuckle (Class 6), A Pact with the Sun (Class 6)',
              'Honeydew & It So Happened (Class 8)',
              'Grammar & Literature, Comprehension Skills',
              'Writing & Communication Skills']}
    ]
  }
};

// ═══ chunks/c05.js ═══
// SYLLABUS DATA — UPSC CSE Prelims
// GS Paper I (200 marks) + CSAT Paper II (200 marks, qualifying 33%)
const syl_upsc_pre = {
  'GS Paper I (200 Marks)': {
    marks:200, color:'#10b981',
    topics:[
      {name:'Current Events — National & International',hindi:'समसामयिक घटनाएं',
       micro:['National events (last 12-18 months)',
              'International events & summits',
              'Government schemes & policies',
              'Awards, appointments, sports',
              "India's foreign policy",
              'International organisations — UN, IMF, WB, WTO, SCO, BRICS, G20']},
      {name:'History of India & Indian National Movement',hindi:'भारत का इतिहास एवं राष्ट्रीय आंदोलन',
       micro:['Ancient India — Indus Valley, Vedic, Buddhism/Jainism, Maurya, Sangam, Gupta',
              'Medieval India — Rajputs, Delhi Sultanate, Vijayanagara, Mughal, Maratha, Bhakti-Sufi',
              'Modern India — British expansion, economic impact, social reforms',
              '1857 Revolt, INC formation, Partition of Bengal',
              'Gandhi era — Non-Cooperation, Civil Disobedience, Quit India',
              'Post-independence consolidation']},
      {name:'Indian & World Geography',hindi:'भारतीय एवं विश्व भूगोल',
       micro:['Physical Geography — Geomorphology, Climatology, Oceanography, Biogeography',
              'Indian Geography — Physiography, Drainage, Climate, Soils, Vegetation, Resources',
              'World Geography — Continents, Countries, Economic Geography',
              'Agriculture, Minerals & Industries',
              'Population & Urbanization','Important map locations']},
      {name:'Indian Polity & Governance',hindi:'भारतीय राजव्यवस्था एवं शासन',
       micro:['Constitution — Historical background, Preamble, Salient features, Amendments',
              'Fundamental Rights (Art 12-35), DPSP (Art 36-51), Fundamental Duties',
              'Parliament — Lok Sabha, Rajya Sabha, Legislative process',
              'President, VP, PM, Council of Ministers',
              'Supreme Court, High Courts, Judicial Review',
              'Federalism, Centre-State relations',
              'Panchayati Raj (73rd, 74th Amendment)',
              'Election Commission, CAG, UPSC, Finance Commission',
              'Constitutional & Non-constitutional bodies',
              'Government schemes & policies']},
      {name:'Economic & Social Development',hindi:'आर्थिक एवं सामाजिक विकास',
       micro:['Basic concepts — GDP, GNP, NNP, Inflation, Deflation, Stagflation',
              'Planning — Five Year Plans, NITI Aayog',
              'Agriculture — Green Revolution, Land reforms, Food security, MSP',
              'Industry — Industrial policy, MSMEs, Make in India, PLI',
              'Banking — RBI, Monetary policy, Types of banks, NPA',
              'Capital markets, FDI, FII, WTO, BOP',
              'Budget — Fiscal policy, Taxes, Deficit types',
              'Poverty, Unemployment, Social sector schemes',
              'Sustainable Development Goals (SDGs)']},
      {name:'Environment, Ecology & Climate Change',hindi:'पर्यावरण, पारिस्थितिकी एवं जलवायु परिवर्तन',
       micro:['Ecology — Ecosystem, Food chain/web, Energy flow, Nutrient cycles',
              'Biodiversity — CBD, CITES, Ramsar, World Heritage, Hotspots',
              'Climate change — UNFCCC, Kyoto Protocol, Paris Agreement, COP summits',
              'Environmental laws — EPA 1986, Forest Act, Wildlife Protection Act',
              'Pollution types & control',
              'Disaster management — NDMA, Sendai Framework',
              'Protected areas — National Parks, Sanctuaries, Biosphere Reserves']},
      {name:'General Science',hindi:'सामान्य विज्ञान',
       micro:['Space — ISRO missions (Chandrayaan-3, Mangalyaan, Gaganyaan, Aditya-L1)',
              'Defence — DRDO, Missiles, Nuclear programme',
              'Biotechnology — GMO, Stem cells, CRISPR-Cas9, Vaccines',
              'IT & AI — Artificial Intelligence, ML, Blockchain',
              'Nanotechnology & Robotics',
              'Energy — Solar, Nuclear, Renewable sources',
              'Health — Diseases, WHO, ICMR',
              'Physics & Chemistry basics (Class 10 level)']}
    ]
  },
  'CSAT Paper II (200 Marks — Qualifying 33%)': {
    marks:200, color:'#3b82f6',
    topics:[
      {name:'Reading Comprehension',hindi:'अपठित गद्यांश बोध',
       micro:['English comprehension passages','Hindi comprehension passages',
              'Critical reasoning from passages','Inference drawing','Vocabulary in context']},
      {name:'Logical Reasoning & Analytical Ability',hindi:'तार्किक तर्क एवं विश्लेषणात्मक क्षमता',
       micro:['Logical deduction & syllogism','Analytical reasoning',
              'Critical thinking','Assumptions & conclusions',
              'Cause & effect, Courses of action']},
      {name:'Decision Making & Problem Solving',hindi:'निर्णय लेना एवं समस्या समाधान',
       micro:['Ethical decision making','Situational analysis',
              'Administrative problem solving','Managerial aptitude']},
      {name:'General Mental Ability',hindi:'सामान्य मानसिक क्षमता',
       micro:['Series — Number, Letter, Symbol','Analogies, Classification',
              'Coding-Decoding, Blood Relations',
              'Direction & Distance, Ranking','Venn Diagrams, Puzzles']},
      {name:'Basic Numeracy & Data Interpretation (Class X)',hindi:'आधारभूत संख्यात्मकता एवं आंकड़ा व्याख्या',
       micro:['Number system & arithmetic','Percentage, Profit & Loss, Ratio & Proportion',
              'Time & Work, Speed & Distance','Simple & Compound Interest',
              'Tables, Bar graphs, Pie charts, Line graphs',
              'Data sufficiency','Mean, Median, Mode']}
    ]
  }
};

// ═══ chunks/c06.js ═══
// SYLLABUS DATA — UPSC CSE Mains
// Qualifying: Paper A Indian Language(300) + Paper B English(300)
// Merit: Essay(250) + GS I-IV(250x4=1000) + Optional(250x2=500) + Interview(275)
const syl_upsc_mains = {
  'Qualifying Paper A — Indian Language (300 Marks)': {
    marks:300, color:'#64748b',
    topics:[
      {name:'Indian Language Paper (Qualifying — Matriculation level)',hindi:'भारतीय भाषा पेपर (अर्हक)',
       micro:['One Indian language from 8th Schedule of Constitution',
              'Comprehension of given passages','Precis writing',
              'Usage & vocabulary','Short essays',
              'Translation from English to Indian language & vice versa',
              'Note: Marks NOT counted in merit ranking — minimum 25% required']}
    ]
  },
  'Qualifying Paper B — English (300 Marks)': {
    marks:300, color:'#64748b',
    topics:[
      {name:'English Paper (Qualifying — Matriculation level)',hindi:'अंग्रेजी पेपर (अर्हक)',
       micro:['Comprehension of given passages','Precis writing',
              'Usage & vocabulary','Short essays',
              'Translation from Indian language to English',
              'Note: Marks NOT counted in merit ranking — minimum 25% required']}
    ]
  },
  'Essay Paper (250 Marks)': {
    marks:250, color:'#f59e0b',
    topics:[
      {name:'Essay Writing — Two Essays (Section A & B)',hindi:'निबंध लेखन',
       micro:['Section A: Philosophical / Abstract topics',
              'Section B: Current issues / Social / Administrative topics',
              'Structure — Introduction, Body, Conclusion',
              'Coherence, Flow & Language quality',
              'Multidimensional analysis (~1000-1200 words each)',
              'Practice topics: Technology & Society, Democracy, Women empowerment, Environment, Ethics in governance']}
    ]
  },
  'GS Paper I (250 Marks)': {
    marks:250, color:'#10b981',
    topics:[
      {name:'Indian Heritage & Culture',hindi:'भारतीय विरासत एवं संस्कृति',
       micro:['Art forms — Classical dance (Bharatnatyam, Kathak, Odissi, Kuchipudi, Manipuri, Mohiniyattam, Kathakali, Sattriya)',
              'Classical music — Hindustani & Carnatic','Folk arts & Tribal arts',
              'Literature — Ancient (Sanskrit, Pali), Medieval, Modern',
              'Architecture — Temple styles (Nagara, Dravida, Vesara), Sultanate, Mughal, Colonial',
              'Sculpture & Painting (Ajanta, Ellora, Miniature, Madhubani)',
              'Philosophy & Religion — Vedanta, Buddhism, Jainism, Sufism, Bhakti',
              'UNESCO World Heritage Sites in India']},
      {name:'Modern Indian History (1757–1947)',hindi:'आधुनिक भारतीय इतिहास',
       micro:['British expansion — Battles, Treaties, Subsidiary Alliance, Doctrine of Lapse',
              'Economic impact — Drain of wealth, Deindustrialisation',
              'Social reforms — Raja Ram Mohan Roy, Brahmo Samaj, Arya Samaj',
              '1857 Revolt — Causes, Nature, Spread, Consequences',
              'Rise of nationalism — INC, Moderates vs Extremists, Partition of Bengal 1905',
              'Gandhi era — Champaran, Non-Cooperation, Civil Disobedience, Quit India',
              'Revolutionary movements — Bhagat Singh, Subhas Chandra Bose, INA',
              'Communalism & Partition 1947']},
      {name:'Post-independence Consolidation',hindi:'स्वतंत्रता पश्चात एकीकरण',
       micro:['Integration of princely states','Reorganisation of states on linguistic basis',
              'Nehruvian era — foreign policy, economic planning',
              'Green Revolution, White Revolution','Emergency 1975-77',
              'Economic liberalisation 1991']},
      {name:'World History (18th–20th Century)',hindi:'विश्व इतिहास',
       micro:['Industrial Revolution & its impact',
              'American Revolution, French Revolution',
              'World War I — Causes, Events, Consequences',
              'World War II — Causes, Events, Holocaust, Consequences',
              'Russian Revolution 1917','Decolonisation of Asia & Africa',
              'Cold War, Non-Aligned Movement',
              'Unification of Germany & Italy']},
      {name:'Indian Society',hindi:'भारतीय समाज',
       micro:['Diversity of India — Caste, Religion, Language, Region',
              "Role of women & women's organisations",
              'Population & associated issues','Poverty & developmental issues',
              'Urbanisation, migration','Communalism, Regionalism, Secularism',
              'Social empowerment']},
      {name:'Physical & Human Geography',hindi:'भौतिक एवं मानव भूगोल',
       micro:['Geomorphology — Earthquakes, Volcanoes, Tsunamis, Cyclones',
              'Climatology — Monsoon, El Nino, La Nina, Climate zones',
              'Oceanography — Ocean currents, Tides, Marine resources',
              'Biogeography — Biomes, Biodiversity',
              'Human Geography — Population distribution, Migration, Urbanisation',
              'Economic Geography — Agriculture, Industry, Trade']}
    ]
  }
};

// ═══ chunks/c07.js ═══
// UPSC Mains GS II, III, IV
const syl_upsc_mains2 = {
  'GS Paper II (250 Marks)': {
    marks:250, color:'#3b82f6',
    topics:[
      {name:'Indian Constitution & Polity',hindi:'भारतीय संविधान एवं राजव्यवस्था',
       micro:['Constitution — Historical underpinnings, Evolution, Features, Amendments',
              'Fundamental Rights, DPSP, Fundamental Duties — detailed analysis',
              'Parliament — Structure, Functions, Powers, Committees',
              'Executive — President, PM, Cabinet, Governor',
              'Judiciary — Supreme Court, High Courts, Judicial activism, PIL',
              'Federalism — Centre-State relations, Inter-state disputes',
              'Constitutional bodies — Election Commission, CAG, UPSC, Finance Commission',
              'Non-constitutional bodies — NITI Aayog, CBI, CVC, Lokpal']},
      {name:'Governance & Public Policy',hindi:'शासन एवं लोक नीति',
       micro:['Good governance — Transparency, Accountability, Rule of law',
              'E-governance — Digital India, MyGov, UMANG',
              'Citizen Charter, RTI Act',
              'Decentralisation — Panchayati Raj, Urban Local Bodies',
              'Civil services — Role, Importance, Reforms',
              'Public policy — Formulation, Implementation, Evaluation',
              'Welfare schemes — Analysis & impact']},
      {name:'Social Justice',hindi:'सामाजिक न्याय',
       micro:['Welfare schemes for vulnerable sections — SC, ST, OBC, Women, Children, Elderly, Disabled',
              'Health — NHM, Ayushman Bharat, Mental health policy',
              'Education — NEP 2020, RTE Act, Higher education reforms',
              'Poverty alleviation — MGNREGA, PM-KISAN, PMAY',
              'Food security — PDS, NFSA','Labour reforms, Skill development']},
      {name:'International Relations',hindi:'अंतर्राष्ट्रीय संबंध',
       micro:['India & Neighbours — Pakistan, China, Bangladesh, Nepal, Sri Lanka, Myanmar, Bhutan',
              'India & major powers — USA, Russia, EU, Japan, Australia',
              "India's foreign policy — Non-Alignment, Strategic autonomy, Neighbourhood First",
              'Diaspora & its role',
              'International organisations — UN system, WTO, IMF, World Bank',
              'Regional groupings — SAARC, BIMSTEC, SCO, ASEAN, QUAD',
              'Global issues — Terrorism, Cyber security, Nuclear non-proliferation']}
    ]
  },
  'GS Paper III (250 Marks)': {
    marks:250, color:'#8b5cf6',
    topics:[
      {name:'Indian Economy & Development',hindi:'भारतीय अर्थव्यवस्था एवं विकास',
       micro:['Economic planning — Five Year Plans, NITI Aayog, SDGs',
              'Inclusive growth — Poverty, Inequality, Employment',
              'Agriculture — Cropping patterns, Irrigation, Storage, Marketing, e-NAM',
              'Land reforms, Green Revolution, Food processing',
              'Industry — Industrial policy, MSMEs, Make in India, PLI schemes',
              'Infrastructure — Roads, Railways, Ports, Airports, Energy',
              'Investment models — PPP, FDI, FII',
              'Monetary policy — RBI, Inflation targeting, Interest rates',
              'Fiscal policy — Budget, Taxes, Deficit, FRBM Act',
              'External sector — BOP, Exchange rate, Trade policy, WTO']},
      {name:'Science & Technology',hindi:'विज्ञान एवं प्रौद्योगिकी',
       micro:['Space technology — ISRO, Chandrayaan-3, Gaganyaan, PSLV, GSLV',
              'Defence technology — DRDO, Agni, BrahMos, INS Vikrant, ASAT',
              'Nuclear technology — DAE, BARC, Nuclear doctrine',
              'Biotechnology — GMO, Stem cells, CRISPR, Biofuels',
              'IT & AI — Artificial Intelligence, ML, Big Data, Blockchain, Quantum computing',
              'Nanotechnology & Robotics',
              'Cybersecurity — Cyber threats, IT Act, CERT-In',
              'Health technology — Vaccines, Drug approvals, Telemedicine']},
      {name:'Environment, Biodiversity & Disaster Management',hindi:'पर्यावरण, जैव विविधता एवं आपदा प्रबंधन',
       micro:['Conservation — Protected areas, Project Tiger, Project Elephant, Wetlands',
              'Biodiversity — Hotspots, Endangered species, Traditional knowledge, ABS',
              'Climate change — UNFCCC, Paris Agreement, NDCs, Carbon markets',
              'Environmental laws — EPA, Forest Act, Wildlife Protection Act, EIA',
              'Pollution — Air, Water, Soil, Plastic, E-waste',
              'Disaster management — NDMA, SDMA, Sendai Framework',
              'Sustainable development — Green economy, Circular economy']},
      {name:'Security Challenges',hindi:'सुरक्षा चुनौतियां',
       micro:['Internal security — Naxalism/LWE, Insurgency in NE India',
              'Terrorism — Domestic & cross-border, Funding, Radicalisation',
              'Border management — India-Pakistan, India-China, Coastal security',
              'Organised crime — Drug trafficking, Human trafficking, Money laundering',
              'Cyber security threats',
              'Role of media & social media in internal security',
              'Security forces — CRPF, BSF, CISF, NSG, RAW, IB']}
    ]
  },
  'GS Paper IV — Ethics (250 Marks)': {
    marks:250, color:'#ef4444',
    topics:[
      {name:'Ethics & Human Interface',hindi:'नीतिशास्त्र एवं मानवीय संपर्क',
       micro:['Essence, determinants & consequences of ethics in human actions',
              'Dimensions of ethics','Ethics in private & public relationships',
              'Human values — Lessons from lives of great leaders, reformers, administrators',
              'Role of family, society & educational institutions in inculcating values']},
      {name:'Attitude & Aptitude',hindi:'अभिवृत्ति एवं अभिरुचि',
       micro:['Attitude — Content, structure, function, influence on thought & behaviour',
              'Moral & political attitudes','Social influence & persuasion',
              'Aptitude & foundational values for civil services',
              'Emotional intelligence — Concepts, utilities, application in administration']},
      {name:'Moral Thinkers & Philosophers',hindi:'नैतिक विचारक एवं दार्शनिक',
       micro:['Contributions of moral thinkers — Plato, Aristotle, Kant, Mill, Gandhi, Ambedkar',
              'Indian ethical thought — Vedanta, Buddhism, Jainism',
              'Public/civil service values — Integrity, Impartiality, Dedication',
              'Status & problems of ethics in public administration']},
      {name:'Probity in Governance',hindi:'शासन में सत्यनिष्ठा',
       micro:['Concept of public service','Philosophical basis of governance & probity',
              'Information sharing & transparency — RTI',
              'Codes of Ethics, Codes of Conduct','Citizen Charter',
              'Work culture, Quality of service delivery',
              'Utilisation of public funds','Challenges of corruption']},
      {name:'Case Studies',hindi:'केस अध्ययन',
       micro:['Case studies on ethical dilemmas in governance',
              'Case studies on conflict of interest',
              'Case studies on whistleblowing',
              'Case studies on disaster management & ethics',
              'Case studies on social justice & administration']}
    ]
  },
  'Optional Subject Paper I & II (500 Marks)': {
    marks:500, color:'#64748b',
    topics:[
      {name:'Optional Subject — Not Yet Selected',hindi:'वैकल्पिक विषय — अभी तक चयन नहीं',
       micro:['Popular choices: History, Geography, Public Administration, Sociology, Political Science & IR, Anthropology, Philosophy, Psychology, Law, Economics',
              'Please select your optional subject and come back to generate a detailed plan',
              'Each optional has 2 papers of 250 marks each',
              'Total: 500 marks counted in final merit',
              'Tip: Choose based on your graduation background & interest']}
    ]
  }
};
// Merge mains objects
Object.assign(syl_upsc_mains, syl_upsc_mains2);

// ═══ chunks/c08.js ═══
// Master syllabusData object + helper functions
const syllabusData = {
  bpsc15: syl_bpsc15,
  bpsc68: syl_bpsc68,
  upsc: { prelims: syl_upsc_pre, mains: syl_upsc_mains }
};

function getSyllabus() {
  if (userData.exam === 'bpsc') {
    if (userData.bpscClass === 'both') {
      const merged = {};
      Object.entries(syl_bpsc15).forEach(([k,v]) => { merged['[1-5] '+k] = v; });
      Object.entries(syl_bpsc68).forEach(([k,v]) => { merged['[6-8] '+k] = v; });
      return merged;
    }
    return userData.bpscClass === '1-5' ? syl_bpsc15 : syl_bpsc68;
  }
  return { ...syl_upsc_pre, ...syl_upsc_mains };
}

function getSubjectsList() {
  const syl = getSyllabus();
  const list = Object.entries(syl).map(([name, data]) => ({
    name, marks: data.marks, color: data.color, topics: data.topics
  }));
  // BPSC: Language is qualifying — schedule last
  if (userData.exam === 'bpsc') {
    const langIdx = list.findIndex(s => s.name.includes('Part I') && s.name.includes('Language'));
    if (langIdx > -1) { const [l] = list.splice(langIdx, 1); list.push(l); }
  }
  return list;
}

function getExamDate() {
  return userData.exam === 'bpsc'
    ? new Date('2026-09-22')
    : new Date('2027-05-16');
}

function generatePlan() {
  const name = document.getElementById('userName').value.trim();
  const startDate = document.getElementById('startDate').value;
  if (!name || !startDate) { alert('कृपया नाम और तारीख भरें!'); return; }

  const hoursEl = document.querySelector('input[name="studyHours"]:checked');
  const hours = hoursEl ? parseInt(hoursEl.value) : 4;

  const slots = [];
  document.querySelectorAll('input[name="slot"]:checked').forEach(s => slots.push(s.value));

  let bpscClass = '';
  if (selectedExam === 'bpsc') {
    const bc = document.querySelector('input[name="bpscClass"]:checked');
    bpscClass = bc ? bc.value : '1-5';
  }

  userData = { name, exam: selectedExam, bpscClass, startDate: new Date(startDate), studyHours: hours, timeSlots: slots };
  studyPlan = buildPlan();
  renderPlan();
  showScreen('planScreen');
}

function buildPlan() {
  const plan = [];
  const examDate = getExamDate();
  const endDate = new Date(examDate);
  endDate.setDate(endDate.getDate() - 15);

  const totalDays = Math.max(1, Math.ceil((endDate - userData.startDate) / 86400000));
  const subjects = getSubjectsList();

  // Per-subject topic pointer — tracks which topic each subject is currently on
  const topicPointers = subjects.map(() => 0);
  // Flat queue: expand all subjects × topics into ordered task list
  // Each task = { subjIdx, topicIdx, microTopics }
  const taskQueue = [];
  let pass = 0;
  while (taskQueue.length < totalDays * 3 + 30) {
    let added = 0;
    subjects.forEach((subj, si) => {
      if (pass < subj.topics.length) {
        taskQueue.push({ si, topicIdx: pass, topic: subj.topics[pass] });
        added++;
      }
    });
    if (added === 0) break;
    pass++;
  }

  let taskIdx = 0;
  let cur = new Date(userData.startDate);

  for (let d = 1; d <= totalDays; d++) {
    const daysLeft = totalDays - d;
    const isMock = daysLeft <= 14 && daysLeft % 7 === 0;
    const isRevision = !isMock && d % 7 === 0;
    const daySlots = [];

    if (isMock) {
      daySlots.push({ type:'mock', subject:'Mock Test', hindi:'मॉक टेस्ट',
        topic:'Full Syllabus Mock Test', microTopics:[], slotType:'morning' });
    } else if (isRevision) {
      // Revision day: revisit last 3 days' topics
      const revTopics = [];
      for (let rb = d - 3; rb < d; rb++) {
        if (plan[rb - 1]) {
          plan[rb - 1].slots.filter(s => s.type === 'subject').forEach(s => {
            revTopics.push(s.topic);
          });
        }
      }
      daySlots.push({ type:'revision', subject:'📖 Revision Day', hindi:'दोहराई',
        topic: revTopics.slice(0, 4).join(' • ') || 'Previous week topics',
        microTopics: revTopics, slotType:'revision' });
    } else {
      // Normal day: 3 subject slots, each with a specific topic
      const slotTypes = ['morning', 'afternoon', 'evening'];
      for (let s = 0; s < 3; s++) {
        if (taskIdx < taskQueue.length) {
          const task = taskQueue[taskIdx++];
          const subj = subjects[task.si];
          const topic = task.topic;
          daySlots.push({
            type: 'subject',
            subject: subj.name,
            color: subj.color || '#f59e0b',
            topic: topic.name,
            hindiTopic: topic.hindi || '',
            microTopics: topic.micro || [],
            slotType: slotTypes[s]
          });
        }
      }
    }

    // 1 hr Revision slot (non-mock, non-revision days)
    if (!isMock && !isRevision && d > 1 && plan[d - 2]) {
      const prev = plan[d - 2].slots.filter(s => s.type === 'subject').map(s => s.topic);
      daySlots.push({ type:'revision', subject:'🔄 Quick Revision', hindi:'दोहराई',
        topic: prev.slice(0, 2).join(' + ') || 'Yesterday\'s topics',
        microTopics: prev, slotType:'revision' });
    }

    // Daily Current Affairs — 30 min every day
    daySlots.push({ type:'current_affairs', subject:'📰 Current Affairs',
      hindi:'समसामयिक घटनाएं', topic:'Daily News + Monthly Magazine (30 min)',
      microTopics:[], slotType:'current' });

    plan.push({
      day: d, date: new Date(cur),
      dayName: cur.toLocaleDateString('en-IN', { weekday: 'short' }),
      slots: daySlots, isMock, isRevision
    });
    cur.setDate(cur.getDate() + 1);
  }
  return plan;
}

// ═══ chunks/c09.js ═══
// renderPlan() + generateDayPlanHTML() — v2 with proper topic display
function renderPlan() {
  const examLabel = userData.exam === 'bpsc'
    ? (userData.bpscClass === '1-5' ? 'BPSC TRE 4.0 — Class 1–5 (PRT)'
      : userData.bpscClass === '6-8' ? 'BPSC TRE 4.0 — Class 6–8 (TGT)'
      : 'BPSC TRE 4.0 — Class 1–5 & 6–8')
    : 'UPSC CSE 2027';

  document.getElementById('planTitle').textContent = `${userData.name} का Study Plan`;
  document.getElementById('planSubtitle').textContent =
    `${examLabel} • ${studyPlan.length} दिन • ${userData.studyHours} घंटे/दिन`;

  const now = new Date();
  const pct = Math.min(100, Math.max(0, Math.round(
    ((now - userData.startDate) / (getExamDate() - userData.startDate)) * 100
  )));
  document.getElementById('planProgressBar').style.width = Math.max(2, pct) + '%';
  const daysLeft = Math.max(0, Math.ceil((getExamDate() - now) / 86400000));
  document.getElementById('planProgressLabel').textContent =
    `${pct}% Complete • परीक्षा में ${daysLeft} दिन बाकी`;

  document.getElementById('planBody').innerHTML = `
    <div class="tab-bar">
      <button class="tab-btn active" onclick="showTab('tabPlan')">📅 Day Plan</button>
      <button class="tab-btn" onclick="showTab('tabSyllabus')">📚 Syllabus</button>
      <button class="tab-btn" onclick="showTab('tabPYQ')">📝 PYQ Tips</button>
      <button class="tab-btn" onclick="showTab('tabInfo')">ℹ️ Exam Info</button>
    </div>
    <div id="tabPlan" class="tab-content active">${generateDayPlanHTML()}</div>
    <div id="tabSyllabus" class="tab-content">${generateSyllabusHTML()}</div>
    <div id="tabPYQ" class="tab-content">${generatePYQsHTML()}</div>
    <div id="tabInfo" class="tab-content">${generateExamInfoHTML()}</div>
  `;
}

const SLOT_META = {
  morning:   { label:'☀️ Morning',   cls:'morning-slot',   time:'6–9 AM'   },
  afternoon: { label:'🌤️ Afternoon', cls:'afternoon-slot', time:'12–3 PM'  },
  evening:   { label:'🌆 Evening',   cls:'evening-slot',   time:'3–6 PM'   },
  revision:  { label:'🔄 Revision',  cls:'revision-slot',  time:'1 hr'     },
  current:   { label:'📰 Current Affairs', cls:'current-slot', time:'30 min' },
};

function generateDayPlanHTML() {
  if (!studyPlan.length) return '<p class="empty-msg">No plan generated.</p>';

  const todayStr = new Date().toDateString();
  const weeks = [];
  for (let i = 0; i < studyPlan.length; i += 7) weeks.push(studyPlan.slice(i, i + 7));

  return weeks.map((week, wi) => {
    const wStart = week[0].date.toLocaleDateString('en-IN', { day:'numeric', month:'short' });
    const wEnd   = week[week.length-1].date.toLocaleDateString('en-IN', { day:'numeric', month:'short' });
    const isCurrentWeek = week.some(d => d.date.toDateString() === todayStr);

    const daysHTML = week.map(day => {
      const isToday = day.date.toDateString() === todayStr;
      const dateStr = day.date.toLocaleDateString('en-IN', { weekday:'long', day:'numeric', month:'long' });

      let dayClass = 'day-card';
      if (isToday) dayClass += ' today-card';
      else if (day.isMock) dayClass += ' mock-day';
      else if (day.isRevision) dayClass += ' revision-day';

      const badge = isToday
        ? '<span class="day-badge badge-today">⚡ Today</span>'
        : day.isMock
          ? '<span class="day-badge badge-mock">🎯 Mock Test</span>'
          : day.isRevision
            ? '<span class="day-badge badge-revision">🔄 Revision Day</span>'
            : '';

      const slotsHTML = day.slots.map(slot => {
        const meta = SLOT_META[slot.slotType] || SLOT_META.morning;

        if (slot.type === 'mock') {
          return `<div class="slot-card mock-slot-card">
            <div class="slot-card-header">
              <span class="slot-type-badge" style="background:rgba(239,68,68,.15);color:#f87171;border-color:rgba(239,68,68,.3)">🎯 Mock Test</span>
              <span class="slot-duration">2–3 hrs</span>
            </div>
            <div class="slot-card-title">Full Syllabus Mock Test</div>
            <div class="slot-card-sub">सभी topics का full-length practice test दें। Time management practice करें।</div>
          </div>`;
        }

        if (slot.type === 'current_affairs') {
          return `<div class="slot-card ca-slot-card">
            <div class="slot-card-header">
              <span class="slot-type-badge" style="background:rgba(239,68,68,.08);color:#fca5a5;border-color:rgba(239,68,68,.2)">📰 Current Affairs</span>
              <span class="slot-duration">30 min</span>
            </div>
            <div class="slot-card-title">Daily News + Monthly Magazine</div>
            <div class="slot-card-sub">The Hindu / Dainik Jagran पढ़ें। Important events note करें।</div>
          </div>`;
        }

        if (slot.type === 'revision') {
          const revList = Array.isArray(slot.microTopics) && slot.microTopics.length
            ? slot.microTopics.slice(0, 4).map(t => `<span class="rev-tag">${t}</span>`).join('')
            : `<span class="rev-tag">${slot.topic}</span>`;
          return `<div class="slot-card rev-slot-card">
            <div class="slot-card-header">
              <span class="slot-type-badge" style="background:rgba(245,158,11,.1);color:#fbbf24;border-color:rgba(245,158,11,.25)">🔄 Revision</span>
              <span class="slot-duration">1 hr</span>
            </div>
            <div class="slot-card-title">Quick Revision</div>
            <div class="rev-tags-wrap">${revList}</div>
          </div>`;
        }

        // Normal subject slot
        const micros = (slot.microTopics || []).slice(0, 4);
        const microsHTML = micros.length
          ? `<ul class="slot-micro-list">${micros.map(m => `<li>${m}</li>`).join('')}</ul>`
          : '';

        const subjectShort = slot.subject.replace(/Part [IVX]+ — /g, '').replace(/\[1-5\] /g,'').replace(/\[6-8\] /g,'');

        return `<div class="slot-card subject-slot-card" style="--slot-color:${slot.color || '#f59e0b'}">
          <div class="slot-card-header">
            <span class="slot-type-badge" style="background:rgba(245,158,11,.1);color:${slot.color||'#f59e0b'};border-color:${slot.color||'#f59e0b'}40">${meta.label}</span>
            <span class="slot-duration">${meta.time}</span>
          </div>
          <div class="slot-part-label">${subjectShort}</div>
          <div class="slot-card-title">${slot.topic}</div>
          ${slot.hindiTopic ? `<div class="slot-card-hindi">${slot.hindiTopic}</div>` : ''}
          ${microsHTML}
        </div>`;
      }).join('');

      return `<div class="${dayClass}">
        <div class="day-header">
          <div class="day-header-left">
            <div class="day-num-circle${isToday ? ' today-circle' : ''}">
              <span class="day-num-label">Day</span>
              <span class="day-num-val">${day.day}</span>
            </div>
            <div class="day-date-info">
              <div class="day-date-main">${dateStr}</div>
              ${badge}
            </div>
          </div>
          <div class="day-slots-count">${day.slots.filter(s=>s.type==='subject').length} subjects</div>
        </div>
        <div class="slots-grid">${slotsHTML}</div>
      </div>`;
    }).join('');

    return `<div class="week-block${isCurrentWeek ? ' current-week' : ''}">
      <div class="week-header">
        <span class="week-title">Week ${wi + 1}</span>
        <span class="week-range">${wStart} – ${wEnd}</span>
        ${isCurrentWeek ? '<span class="week-now-badge">Current Week</span>' : ''}
      </div>
      <div class="week-days">${daysHTML}</div>
    </div>`;
  }).join('');
}

// ═══ chunks/c10.js ═══
// generateSyllabusHTML()
function generateSyllabusHTML() {
  const syl = getSyllabus();
  const parts = Object.entries(syl).map(([partName, partData]) => {
    const color = partData.color || 'var(--amber)';
    const topics = (partData.topics || []).map(topic => {
      const micros = (topic.micro || []).map(m => `<li>${m}</li>`).join('');
      return `<div class="subtopic">
        <div class="subtopic-name">${topic.name}</div>
        <div class="subtopic-hindi">${topic.hindi || ''}</div>
        <ul class="micro-list">${micros}</ul>
      </div>`;
    }).join('');

    return `<div class="syl-subject" style="border-left-color:${color}">
      <div class="syl-head" onclick="toggleAccordion(this)">
        <div class="syl-head-left">
          <span class="syl-head-title">${partName}</span>
        </div>
        <div class="syl-head-right">
          <span class="syl-marks">${partData.marks} Marks</span>
          <span class="syl-arrow">▼</span>
        </div>
      </div>
      <div class="syl-body">${topics}</div>
    </div>`;
  }).join('');

  return `<div class="section-block">
    <h3>📚 Complete Syllabus</h3>
    ${parts}
  </div>`;
}

// ═══ chunks/c11.js ═══
// generatePYQsHTML() + generateExamInfoHTML()
function generatePYQsHTML() {
  const isBpsc = userData.exam === 'bpsc';
  if (isBpsc) {
    return `<div class="section-block">
      <h3>📝 BPSC TRE — PYQ Analysis & Tips</h3>
      <div class="pyq-grid">
        <div class="pyq-card">
          <h5>🔢 Mathematics (Most Asked)</h5>
          <ul>
            <li>Percentage & Profit-Loss (8–10 Qs)</li>
            <li>Time & Work, Speed-Distance (6–8 Qs)</li>
            <li>Number System & Simplification</li>
            <li>Mensuration — Area, Volume</li>
            <li>Average, Ratio & Proportion</li>
          </ul>
        </div>
        <div class="pyq-card">
          <h5>🧠 Reasoning (High Scoring)</h5>
          <ul>
            <li>Series — Number & Letter (5–6 Qs)</li>
            <li>Blood Relations (3–4 Qs)</li>
            <li>Coding-Decoding (3–4 Qs)</li>
            <li>Direction Sense (2–3 Qs)</li>
            <li>Syllogism & Venn Diagram</li>
          </ul>
        </div>
        <div class="pyq-card">
          <h5>🌍 GS — History & Polity</h5>
          <ul>
            <li>Freedom Movement — Gandhi, INC</li>
            <li>Bihar History — Champaran, JP</li>
            <li>Constitution — FR, DPSP, Amendments</li>
            <li>Panchayati Raj (73rd, 74th)</li>
            <li>President, PM, Parliament</li>
          </ul>
        </div>
        <div class="pyq-card">
          <h5>🔬 Science (Easy Marks)</h5>
          <ul>
            <li>Biology — Diseases, Vitamins, Cells</li>
            <li>Physics — Force, Motion, Light</li>
            <li>Chemistry — Acids, Metals, Reactions</li>
            <li>Environment — Pollution, Ecosystem</li>
            <li>Current Science News</li>
          </ul>
        </div>
      </div>
      <div class="ca-box">
        <h4>📰 Daily Current Affairs Strategy</h4>
        <ul>
          <li>The Hindu / Dainik Jagran — 30 min daily</li>
          <li>Monthly Magazine: Pratiyogita Darpan / Arihant</li>
          <li>Bihar Current Affairs — Prabhat Khabar</li>
          <li>Government Schemes — PIB.gov.in</li>
        </ul>
      </div>
    </div>`;
  }
  return `<div class="section-block">
    <h3>📝 UPSC CSE — PYQ Analysis & Tips</h3>
    <div class="pyq-grid">
      <div class="pyq-card">
        <h5>🏛️ Polity & Governance (Prelims)</h5>
        <ul>
          <li>Constitution — Articles, Amendments (8–10 Qs)</li>
          <li>Parliament, President, PM (5–6 Qs)</li>
          <li>Constitutional Bodies (4–5 Qs)</li>
          <li>Panchayati Raj, Local Bodies</li>
          <li>Recent SC Judgements</li>
        </ul>
      </div>
      <div class="pyq-card">
        <h5>🌿 Environment & Ecology</h5>
        <ul>
          <li>Biodiversity — IUCN, Ramsar, CITES (5–7 Qs)</li>
          <li>Climate Change — Paris, COP (4–5 Qs)</li>
          <li>National Parks & Sanctuaries</li>
          <li>Environmental Laws</li>
          <li>Pollution & Disaster Management</li>
        </ul>
      </div>
      <div class="pyq-card">
        <h5>📜 History & Culture</h5>
        <ul>
          <li>Ancient India — Indus, Maurya, Gupta (5–6 Qs)</li>
          <li>Medieval — Mughal, Bhakti-Sufi (4–5 Qs)</li>
          <li>Modern — Freedom Movement (6–8 Qs)</li>
          <li>Art & Architecture (3–4 Qs)</li>
          <li>UNESCO Heritage Sites</li>
        </ul>
      </div>
      <div class="pyq-card">
        <h5>💰 Economy (Trending)</h5>
        <ul>
          <li>Budget — Fiscal Deficit, Taxes (4–5 Qs)</li>
          <li>RBI, Monetary Policy, Inflation</li>
          <li>Agriculture — MSP, e-NAM, FCI</li>
          <li>International — WTO, IMF, World Bank</li>
          <li>Government Schemes — PLI, PM-KISAN</li>
        </ul>
      </div>
    </div>
    <div class="pyq-links">
      <a class="pyq-link" href="https://upsc.gov.in/examinations/previous-question-papers" target="_blank">📄 UPSC Official PYQs</a>
      <a class="pyq-link" href="https://www.insightsonindia.com/upsc-previous-year-question-papers/" target="_blank">📚 Insights PYQ Analysis</a>
    </div>
    <div class="ca-box">
      <h4>📰 Daily Current Affairs Strategy</h4>
      <ul>
        <li>The Hindu + Indian Express — 1 hr daily</li>
        <li>PIB.gov.in — Government press releases</li>
        <li>Monthly: Vision IAS / Insights Current Affairs</li>
        <li>Yojana & Kurukshetra — Monthly magazines</li>
      </ul>
    </div>
  </div>`;
}

function generateExamInfoHTML() {
  const isBpsc = userData.exam === 'bpsc';
  if (isBpsc) {
    const cls = userData.bpscClass;
    return `<div class="section-block">
      <h3>ℹ️ BPSC TRE 4.0 — Exam Information</h3>
      <div class="info-grid">
        <div class="info-card">
          <h4>📅 Important Dates</h4>
          <p><strong>Exam Date:</strong> Sep 2026 (Tentative)</p>
          <p><strong>Notification:</strong> BPSC Official</p>
          <p><strong>Plan Ends:</strong> 15 days before exam</p>
        </div>
        <div class="info-card">
          <h4>📝 Exam Pattern</h4>
          ${cls === '1-5' || cls === 'both' ? `<p><strong>Class 1–5 (PRT):</strong></p>
          <p>Part I Language: 30 marks</p>
          <p>Part II GS: 120 marks</p>
          <p><strong>Total: 150 marks</strong></p>` : ''}
          ${cls === '6-8' || cls === 'both' ? `<p><strong>Class 6–8 (TGT):</strong></p>
          <p>Part I Language: 30 marks</p>
          <p>Part II GS: 40 marks</p>
          <p>Part III Subject: 80 marks</p>
          <p><strong>Total: 150 marks</strong></p>` : ''}
        </div>
        <div class="info-card">
          <h4>✅ Key Rules</h4>
          <p>❌ No Negative Marking</p>
          <p>⏱️ Duration: 2.5 hours</p>
          <p>📋 MCQ format</p>
          <p>🏫 46,595 Total Vacancies</p>
        </div>
        <div class="info-card">
          <h4>📚 Best Books</h4>
          <p>• NCERT Class 6–10 (all subjects)</p>
          <p>• Lucent's GK (Hindi/English)</p>
          <p>• Arihant BPSC TRE Guide</p>
          <p>• R.S. Aggarwal — Maths & Reasoning</p>
        </div>
      </div>
    </div>`;
  }
  return `<div class="section-block">
    <h3>ℹ️ UPSC CSE 2027 — Exam Information</h3>
    <div class="info-grid">
      <div class="info-card">
        <h4>📅 Important Dates</h4>
        <p><strong>Prelims:</strong> May 2027</p>
        <p><strong>Mains:</strong> Sep–Oct 2027</p>
        <p><strong>Interview:</strong> Jan–Apr 2028</p>
        <p><strong>Plan Ends:</strong> 15 days before Prelims</p>
      </div>
      <div class="info-card">
        <h4>📝 Prelims Pattern</h4>
        <p>GS Paper I: 200 marks (100 Qs)</p>
        <p>CSAT Paper II: 200 marks (qualifying 33%)</p>
        <p>Negative marking: -0.66 per wrong</p>
        <p>Duration: 2 hrs each paper</p>
      </div>
      <div class="info-card">
        <h4>📝 Mains Pattern</h4>
        <p>Qualifying: Paper A + B (300+300)</p>
        <p>Essay: 250 marks</p>
        <p>GS I–IV: 250×4 = 1000 marks</p>
        <p>Optional I+II: 250×2 = 500 marks</p>
        <p>Interview: 275 marks</p>
        <p><strong>Total Merit: 2025 marks</strong></p>
      </div>
      <div class="info-card">
        <h4>📚 Standard Books</h4>
        <p>• NCERT 6–12 (all subjects)</p>
        <p>• Laxmikanth — Indian Polity</p>
        <p>• Bipin Chandra — Modern History</p>
        <p>• Ramesh Singh — Indian Economy</p>
        <p>• Shankar IAS — Environment</p>
      </div>
    </div>
    <div class="optional-note">
      <h4>⚠️ Optional Subject</h4>
      <p>आपने अभी तक Optional Subject नहीं चुना है। Popular choices: <strong>History, Geography, Public Administration, Sociology, Political Science & IR, Anthropology, Philosophy, Psychology</strong>. अपने graduation background और interest के हिसाब से चुनें। Optional चुनने के बाद वापस आकर plan generate करें।</p>
    </div>
  </div>`;
}

// ═══ chunks/c12.js ═══
// downloadPDF() with watermark "Er. Sangam Krishna"
function downloadPDF() {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const W = 210, H = 297;
  const margin = 15;
  let y = margin;

  function addWatermark() {
    doc.saveGraphicsState();
    doc.setGState(new doc.GState({ opacity: 0.07 }));
    doc.setFontSize(38);
    doc.setTextColor(180, 120, 0);
    doc.setFont('helvetica', 'bold');
    for (let wy = 50; wy < H; wy += 70) {
      for (let wx = 10; wx < W; wx += 90) {
        doc.text('Er. Sangam Krishna', wx, wy, { angle: 35 });
      }
    }
    doc.restoreGraphicsState();
  }

  function newPage() {
    addWatermark();
    doc.addPage();
    y = margin;
  }

  function checkY(needed) {
    if (y + needed > H - margin) newPage();
  }

  // ── Cover Page ──
  doc.setFillColor(8, 14, 26);
  doc.rect(0, 0, W, H, 'F');
  addWatermark();

  doc.setFontSize(28);
  doc.setTextColor(245, 158, 11);
  doc.setFont('helvetica', 'bold');
  doc.text('ParikshaSathi', W / 2, 60, { align: 'center' });

  doc.setFontSize(13);
  doc.setTextColor(200, 200, 200);
  doc.setFont('helvetica', 'normal');
  doc.text('Personalized Study Plan', W / 2, 72, { align: 'center' });

  doc.setFontSize(18);
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.text(userData.name || 'Student', W / 2, 95, { align: 'center' });

  const examLabel = userData.exam === 'bpsc'
    ? ('BPSC TRE 4.0 — Class ' + (userData.bpscClass === 'both' ? '1–5 & 6–8' : userData.bpscClass))
    : 'UPSC CSE 2027';
  doc.setFontSize(13);
  doc.setTextColor(245, 158, 11);
  doc.text(examLabel, W / 2, 108, { align: 'center' });

  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  doc.text(`Generated: ${new Date().toLocaleDateString('en-IN')}`, W / 2, 120, { align: 'center' });
  doc.text(`Total Days: ${studyPlan.length} | ${userData.studyHours} hrs/day`, W / 2, 128, { align: 'center' });

  doc.setFontSize(11);
  doc.setTextColor(245, 158, 11);
  doc.text('Made with love by Er. Sangam Krishna', W / 2, H - 25, { align: 'center' });
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text('pariksha-sathi.github.io | Free Study Planner', W / 2, H - 17, { align: 'center' });

  // ── Plan Pages ──
  doc.addPage();
  y = margin;
  addWatermark();

  doc.setFontSize(16);
  doc.setTextColor(245, 158, 11);
  doc.setFont('helvetica', 'bold');
  doc.text('Day-by-Day Study Plan', margin, y);
  y += 10;

  studyPlan.forEach(day => {
    checkY(30);
    doc.setFontSize(10);
    doc.setTextColor(245, 158, 11);
    doc.setFont('helvetica', 'bold');
    const dateStr = day.date.toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: '2-digit' });
    doc.text(`Day ${day.day} — ${dateStr} (${day.dayName})${day.isMock ? ' [MOCK TEST]' : day.isRevision ? ' [REVISION]' : ''}`, margin, y);
    y += 5;

    day.slots.forEach(slot => {
      checkY(7);
      doc.setFontSize(8.5);
      doc.setTextColor(220, 220, 220);
      doc.setFont('helvetica', 'normal');
      const icon = slot.type === 'mock' ? '[MOCK]'
        : slot.type === 'revision' ? '[REV]'
        : slot.type === 'current_affairs' ? '[CA]'
        : '[' + (slot.slotType || 'study').toUpperCase().slice(0, 3) + ']';
      const line = `  ${icon} ${slot.subject}: ${slot.topic}`;
      doc.text(line.slice(0, 95), margin + 3, y);
      y += 5.5;
    });

    doc.setDrawColor(40, 60, 90);
    doc.line(margin, y, W - margin, y);
    y += 3;
  });

  addWatermark();

  // ── Save ──
  const safeName = (userData.name || 'Student').replace(/\s+/g, '_');
  const filename = userData.exam === 'bpsc'
    ? `BPSC_TRE4_StudyPlan_${safeName}_SangamKrishna.pdf`
    : `UPSC2027_StudyPlan_${safeName}_SangamKrishna.pdf`;
  doc.save(filename);
}

// ═══ chunks/c13.js ═══
// Canvas particle animation + DOMContentLoaded init
function initCanvas() {
  const canvas = document.getElementById('bgCanvas');
  if (!canvas) return;
  const ctx = canvas.getContext('2d');
  let W, H, particles = [];

  function resize() {
    W = canvas.width = window.innerWidth;
    H = canvas.height = window.innerHeight;
  }
  resize();
  window.addEventListener('resize', resize);

  function Particle() {
    this.x = Math.random() * W;
    this.y = Math.random() * H;
    this.r = Math.random() * 1.5 + 0.3;
    this.vx = (Math.random() - 0.5) * 0.3;
    this.vy = (Math.random() - 0.5) * 0.3;
    this.alpha = Math.random() * 0.5 + 0.1;
    this.color = Math.random() > 0.6 ? '245,158,11' : Math.random() > 0.5 ? '16,185,129' : '59,130,246';
  }

  for (let i = 0; i < 90; i++) particles.push(new Particle());

  function draw() {
    ctx.clearRect(0, 0, W, H);
    particles.forEach(p => {
      p.x += p.vx; p.y += p.vy;
      if (p.x < 0) p.x = W; if (p.x > W) p.x = 0;
      if (p.y < 0) p.y = H; if (p.y > H) p.y = 0;
      ctx.beginPath();
      ctx.arc(p.x, p.y, p.r, 0, Math.PI * 2);
      ctx.fillStyle = `rgba(${p.color},${p.alpha})`;
      ctx.fill();
    });
    // Draw connecting lines between nearby particles
    for (let i = 0; i < particles.length; i++) {
      for (let j = i + 1; j < particles.length; j++) {
        const dx = particles[i].x - particles[j].x;
        const dy = particles[i].y - particles[j].y;
        const dist = Math.sqrt(dx * dx + dy * dy);
        if (dist < 100) {
          ctx.beginPath();
          ctx.moveTo(particles[i].x, particles[i].y);
          ctx.lineTo(particles[j].x, particles[j].y);
          ctx.strokeStyle = `rgba(245,158,11,${0.06 * (1 - dist / 100)})`;
          ctx.lineWidth = 0.5;
          ctx.stroke();
        }
      }
    }
    requestAnimationFrame(draw);
  }
  draw();
}

document.addEventListener('DOMContentLoaded', () => {
  initCanvas();
  // Set default start date to today
  const today = new Date().toISOString().split('T')[0];
  const sd = document.getElementById('startDate');
  if (sd) { sd.value = today; sd.min = today; }
});
