#!/usr/bin/env python3
# ParikshaSathi — build.py
# Merges all chunks into app.js

import os

chunks = [
    'chunks/c00.js',
    'chunks/c01.js',
    'chunks/c02.js',
    'chunks/c03.js',
    'chunks/c04.js',
    'chunks/c05.js',
    'chunks/c06.js',
    'chunks/c07.js',
    'chunks/c07b.js',
    'chunks/c08.js',
    'chunks/c09.js',
    'chunks/c10.js',
    'chunks/c11.js',
    'chunks/c12.js',
    'chunks/c13.js',
    'chunks/c14.js',
    'chunks/c15.js',
    'chunks/c16.js',
    'chunks/c17.js',
    'chunks/c18.js',
    'chunks/c19.js',
    'chunks/c20.js',
    'chunks/c21.js',
    'chunks/c22.js',
    'chunks/c23.js',
    'chunks/c24.js',
]

output = '// ParikshaSathi — app.js (auto-generated by build.py)\n// By Er. Sangam Krishna\n// DO NOT EDIT DIRECTLY — edit chunks/ files and run build.py\n\n'

for chunk in chunks:
    if not os.path.exists(chunk):
        print(f'ERROR: {chunk} not found!')
        exit(1)
    with open(chunk, 'r', encoding='utf-8') as f:
        content = f.read().strip()
    output += f'\n// ═══ {chunk} ═══\n{content}\n'

with open('app.js', 'w', encoding='utf-8') as f:
    f.write(output)

print(f'✅ app.js built successfully ({len(output)} chars, {len(output.splitlines())} lines)')
